---
site_name: 'Introduction to Python Workshop'
repo_url: 'https://github.com/MonashDataFluency/python-workshop-base'
edit_uri: 'blob/master/README.md#modifying-and-building'
site_description: 'Monash Data Fluency Python Workshops'
theme: cinder
# theme: windmill
# theme: cluster
# theme: bootswatch

extra_css:
  - css/extra.css

pages:
  - 'Home': 'index.md'
  - 'Modules':
    - 'Introduction - the basics of Python': 'modules/intro.md'
    - 'Working with Data': 'modules/working_with_data.md'
    - 'Missing values': 'modules/missing_values.md'
    - 'Indexing': 'modules/indexing.md'
    - 'Loops': 'modules/loops.md'
    - 'Combining DataFrames with Pandas': 'modules/merging.data.md'
    - 'Plotting with ggplot for Python': 'modules/plotting_with_ggplot.md'
    - 'Reusable and modular code with functions': 'modules/functions.md'
    - 'Defensive Programming': 'modules/defensive_programming.md'
  - 'Half Day Course': 'halfday.md'
  - 'Full Day Course': 'fullday.md'
