---
site_name: Introduction to Python Workshop
repo_url: https://github.com/MonashDataFluency/python-workshop-base
edit_url: https://github.com/MonashDataFluency/python-workshop-base/tree/master/workshops/docs/modules/notebooks
site_description: Monash Data Fluency Python Workshops
theme: cinder
# theme: windmill
# theme: cluster
# theme: bootswatch

extra_css:
  - css/extra.css

pages:
  - 'Home': 'index.md'
  - 'Modules':
    - 'Introduction - the basics of Python': 'modules/intro.md'
    - 'Working with Data': 'modules/working_with_data.md'
    - 'Indexing': 'modules/indexing.md'
    - 'Loops': 'modules/loops.md'
    - 'Plotting with ggplot for Python': 'modules/plotting_with_ggplot.md'
  - 'Half Day Course': 'halfday.md'
  - 'Full Day Course': 'fullday.md'
